spring:  
  application:
    name: zuuldemo

server:  
  port: 8080

ribbon:
  eureka:
    enabled: false

zuul:
  routes:
    publications:
      path: /api/publication/**
      url: http://localhost:8090